config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:show, :edit, :update, :index]
  post 'follow/:id', to: 'relationships#create', as: 'follow'
  post 'unfollow/:id', to: 'relationships#destroy', as: 'unfollow'
  get 'users/following/:user_id', to: 'relationships#following', as:'users_following'
  get 'users/follower/:user_id', to: 'relationships#follower', as:'users_follower'
  

  
  get 'home/about' => 'users#new'
  root to: 'books#new'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book, counter_cache: :favorites_count
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーをアンフォローする
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしているかを確認する
  def following?(user)
    following_user.include?(user)
  end

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  def reset_user_session
    session[:user_id] = nil
    @current_user = nil
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
 def after_sign_in_path_for(resource)
  user_path(resource)
  end 
  def after_sign_out_path_for(resource)
    root_path
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController



  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book.id)
  end
  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])  
  end
  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:new]

  def new

  end 
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if @book.save
      redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render 'index'
    end
  end
  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end
  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @newbook = Book.new
    @user = @book.user

  end

  def edit
    @book = Book.find(params[:id])  
    if  @book.user == current_user
      render 'edit'
     else 
      redirect_to books_path
     end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
   
    redirect_to book_path(@book), notice: "Book was successfully updated."
    else
    render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
      redirect_to books_path(@books)
  
  end

  private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_book
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def create
    @favorite = current_user.favorites.new(:book_id=>params[:book_id])
    @favorite.save
    @favorites = Favorite.where(book_id: params[:book_id])
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
    favorite.destroy
    @favorites = Favorite.where(book_id: params[:book_id])
  end
  private

  def set_book
    @book = Book.find(params[:book_id])
  end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:id])
    current_user.follow(params[:id])

  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(params[:id])

  end

  def following
    @user = User.find(params[:user_id])
    @followings = @user.following_user.where.not(id: current_user.id)
  end

  # 自分をフォローしているユーザー一覧
  def follower
    @user = User.find(params[:user_id])
    @followers = @user.follower_user.where.not(id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end
  def show
    @users = User.all
    @user = User.find(params[:id])  
    @book = Book.new
 
  end
  def edit
    @user = User.find(params[:id])
   if  @user == current_user
    render 'edit'
   else 
    redirect_to user_path(current_user.id)
   end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated user successfully."
   else
    render 'edit'
    end
  end
  

  private 
  def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
<thead>
   <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colespan="3"></th>
   </tr>
 </thead>
  <tbody>      
   <% books.each do |book| %>
    <tr>
       <td><%= link_to user_path(book.id) do %>
       <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
       <% end %></td>
       <td><%= link_to book.title , book_path(book.id) %></td>
       <td><%= book.body %></td>   
       <td>
         <div class=<%= "favorites_buttons_" + book.id.to_s %>>
         <%= render partial: 'favorites/favorite', locals: { book: book} %>
         </div>
       </td>
         
       <td>コメント数:<%= book.book_comments.count %></td>
     </tr>
   <% end %>
 </tbody>
</table>

app/views/books/_list.html.erb
<div class="col-xs-3">
  <h2>'User info'</h2>
  <p><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></p>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
      <th>name</th>
      <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th> follow</th>
        <th>
          <div id='following-count_#{ user.id }'>
            <%= link_to "#{ user.follower.count }", users_following_path(user) %>
          </div>
        </th>
      </tr>    
      <tr>
      <th>follower</th>
      <th>
        <div id='follower-count_#{ user.id }'>  
          <%= link_to "#{ user.followed.count }", users_follower_path(user) %>  
        </div>
      </th>
      </tr>
      <th>
      <% unless user == current_user %>
      <div class='follow_button_<%= user.id%>' >
        <%= render 'users/follow_button', user: user %>
       </div>
    <% end %>    
      </th>
    </tbody>
  </table>
  <%= link_to "", edit_user_path(@user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  

  <h2>New book</h2>
  <%= form_for(book) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class: "col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label>Opinion</label>
    <%= f.text_area :body,class: "col-xs-12 book_body" %>
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book',class: "btn btn-primary col-xs-12" %>
  </div>
  <% end %>
  

</div>

app/views/books/edit.html.erb
<body>
  <h1>Editing Book</h1>
  <%= form_for(@book) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class=field>
      <label>Title</label>
      <%= f.text_field :title %>
    </div>
    
    <div class=field>
      <label>Body</label>
      <%= f.text_area :body %><br>
    </div>
    
    <div class=actions>
      <%= f.submit 'Update Book' %><br>
    </div>
    
    <%= link_to "Show", book_path(@book) %>
    |
    <%= link_to "Back", books_path %>
    
    <% end %>
  </body>

app/views/books/index.html.erb
<div class="body">
  <div class="container">   
      <div class="row">
        <%= render 'books/list', book: @book, user: @user %>

        <div class="col-xs-9">
          <p id="notice"></p>
          <h2>Books</h2>
            <%= render 'index',books:@books %>
        </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="body">
<p id="notice"><%= flash[:notice] %></p>
 <div class="row">   
   <div class="container">
      <div class="top-message col-md-offset-3 col-md-6">
      
        <h1>"welcome to"<span class="glyphicon glyphicon-book"> <strong>Bookers</strong>!!<span></h1>
        <p>In<span class="glyphicon glyphicon-book"> <strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper">
          <div class="row">
            <p><%= link_to "Log in", new_user_session_path,class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p> 
          </div>
          <div class="row">
            <p><%= link_to "Sign Up", new_user_registration_path,class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up"  %></p> 
          </div>
        </div>    
      </div>  
     </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
  <% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end  %>
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <%= render 'books/list', book: @book, user: @user %>
      <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
              <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
              <br><%= link_to @user.name, user_path(@user) %></td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <td>
                <div class="favorites_buttons_<%= @book.id %>">
                <%= render partial: 'favorites/favorite', locals: { book: @book} %>
                </div>
              </td>
              <td>コメント数:<%= @book.book_comments.count %></td>
              <% if @book.user == current_user %>
              <td> <%= link_to "Edit", edit_book_path(@book),class: "btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn-sm btn-danger" %></td> 
              <% end %>
            </tr>
          </tbody>
            </table>
            <table class="table">
              <tbody>
                <tr>
                  <h3>コメント一覧</h3>
                  <% @book.book_comments.each do |book_comment| %>
                    <tr>
                    <td>
                      <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg") %>
                      <p><%= book_comment.user.name %></p>
                    </td>
                    <td><%= book_comment.comment %></td>
                    <% if book_comment.user == current_user %>
                    <td><%= link_to '削除',book_book_comment_path(book_comment.book, book_comment), method: :delete,data: {confirm:'削除してもよろしいですか？'},class: "btn-sm btn-danger" %></td>
                    </tr>
                    <% end %>
                  <% end %>
                </tr>
               </tbody>
             </table>
              
                <%= form_for [@book, @book_comment] do |f| %>
                  <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %><br>
                  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                <% end %>
              
      </div>
   </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %> 
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.favorites_buttons_'+<%= @favorite.book_id %>).html("<%= j(render partial: 'favorites/favorite', locals: {book: @favorite.book, user: @favorite.user}) %>");

app/views/favorites/destroy.js.erb
$('.favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class="alert alert-warning">
      <ul>
        <% model.errors.full_messages.each do |message| %>
          <li>error<%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5b6bab02f4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right" >
            <% if user_signed_in? %>
              <li>
                <%= link_to 'Home', user_path(current_user.id),class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to 'Users', users_path,class: "glyphicon glyphicon-user user" %>
              </li>
              <li>
                <%= link_to 'Books', books_path,class: "glyphicon glyphicon-book books" %>
              </li> 
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete,class: "glyphicon glyphicon-log-out logout" %>
              </li>
            <% else %>
              <li>
                <%= link_to ' Home', root_path,class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
              <%= link_to ' About', home_about_path,class: "glyphicon glyphicon-link about" %>
            </li>
              <li>
                <%= link_to " Sign up", new_user_registration_path,class: "glyphicon glyphicon-edit sign_up" %>
              </li>
              <li>
                <%= link_to " Login", new_user_session_path,class: "glyphicon glyphicon-log-in login" %>
              </li>
            <% end %> 
          </ul>
        </nav>
      </div>    
    </header>
  <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>   
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/create.js.erb
$(".follow_button_<%= @user.id %>").html("<%= j(render 'users/follow_button', user: @user) %>");

app/views/relationships/destroy.js.erb
$(".follow_button_<%= @user.id %>").html("<%= j(render 'users/follow_button', user: @user) %>");

app/views/relationships/follower.html.erb
<h1>Follower Users</h1>
<table class="table table-hover table-inverse">
<thead>
   <tr>
     <th>image</th>
     <th>name</th>
     <th colespan="3"></th>
   </tr>
 </thead>
  <tbody>      
   <% @followers.each do |follower| %>
    <tr>
       <td>
       <%= attachment_image_tag follower, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
       </td>
       <td><%= follower.name %></td>   
       <td>
        <%= follower.following_user.count %>フォロー中
      </td> 
       <td>  
        <%= follower.follower_user.count %>フォロワー
       </td>
       <td><%= link_to "Show", user_path(follower) %></td>
         
     </tr>
   <% end %>
 </tbody>
</table>

app/views/relationships/following.html.erb
<h1>Follow Users</h1>
<table class="table table-hover table-inverse">
<thead>
   <tr>
     <th>image</th>
     <th>name</th>
     <th>フォロー数</th>
     <th>フォロワー数</th>
     <th colespan="3"></th>
   </tr>
 </thead>
  <tbody>      
   <% @followings.each do |following| %>
    <tr>
       <td>
       <%= attachment_image_tag following, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
       </td>
       <td><%= following.name %></td>   
       <td>
        <%= following.following_user.count %>フォロー中
      </td> 
       <td>  
        <%= following.follower_user.count %>フォロワー
       </td>
       <td><%= link_to "Show", user_path(following) %></td>
     </tr>
   <% end %>
 </tbody>
</table>

app/views/users/_follow_button.html.erb
<% if current_user.following?(user) %>
  <%= link_to 'フォロー解除', unfollow_path(user), method: :post, class: 'btn btn-info', remote: true %>
<% else %>
  <%= link_to 'フォローする', follow_path(user), method: :post, class: 'btn btn-default', remote: true %>
<% end %>

app/views/users/edit.html.erb
<body>
  <h1>User info</h1>
  <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class=field>
      <label>Name</label>
      <%= f.text_field :name %>
    </div>

    <div class="form-group has-icon">
    <div class="user-edit-image">
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb" %>
    </div>
    <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form", fallback: "no_image.jpg" %>
    </div>          
    
    <div class=field>
      <label>Introduction</label>
      <%= f.text_area :introduction %><br>
    </div>
    
    <div class=actions>
      <%= f.submit 'Update User' %><br>
    </div>
    
    <% end %>
  </body>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
      <div class="row">
        <%= render 'books/list', book: @book, user: @user, users: @users %>
        <div class="col-xs-9">
          <h1>Users</h1>

          <table class="table">
            <thead>
              <tr>
                <th>Image</th>
                <th>name</th>
                <th colespan="3"></th>
              </tr>
            </thead>
            <tbody>      
              <% @users.each do |user| %>
              <tr>
                  <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
                  <td><%= user.name %></td>
                  <td>
                  <%= user.following_user.count %>フォロー中
                </td> 
                 <td>  
                  <%= user.follower_user.count %>フォロワー
                 </td>
                 <td>
                    <% unless user == current_user %>
                      <div class='follow_button_<%= user.id%>' >
                        <%= render 'users/follow_button', user: user %>
                       </div>
                    <% end %>      
                  </td>
                  <td><%= link_to "Show", user_path(user.id) %></td>           
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>  
      </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="body">
  <div class="container">
    <h1>"welcome to"<span class="glyphicon glyphicon-book"> <strong>Bookers</strong>!!<span></h1>
  </div>
</div>

app/views/users/show.html.erb
  <div class="body">
  <p id="notice"><%= flash[:notice] %></p>
    <div class="container">
      <div class="row">
        <%= render 'books/list', book: @book, user: @user %>
        <div class="col-xs-9">
          <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colespan="3"></th>
              </tr>
            </thead>
            <tbody>      
              <% @user.books.each do |book| %>
              <tr>
                  <td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
                  <td><%= link_to book.title , book_path(book.id) %></td>
                  <td><%= book.body %></td>
                  <td>コメント数:<%= book.book_comments.count %></td>
                <td></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>